name: Tag-Beta

on:
  push:
    tags:
      - 'v*.*.*-beta*'
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "lol" | grep "o"
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}